export const CHANGE_MENU_STATUS = "CHANGE_MENU_STATUS";
export const SLICE_RANDOM_TOP_PRODUCT_LIST = "SLICE_RANDOM_TOP_PRODUCT_LIST";
export const END_DATA_PRODUCT_DETAILS = "END_DATA_PRODUCT_DETAILS";
export const CHANGE_QTY_PRODUCT = "CHANGE_QTY_PRODUCT";
export const SET_QTY_ENTER_VALUE = "SET_QTY_ENTER_VALUE";
export const CHOOSE_IMG = "CHOOSE_IMG";
export const START_DATA_PRODUCT_DETAILS = "START_DATA_PRODUCT_DETAILS";
export const SET_DATA_PRODUCT_DETAILS = "SET_DATA_PRODUCT_DETAILS";
export const ADD_TO_CART = "ADD_TO_CART";
export const GET_PRODUCTS_DETAILS_CART = "GET_PRODUCTS_DETAILS_CART";
export const ERROR_DATA_PRODUCT_DETAILS = "ERROR_DATA_PRODUCT_DETAILS";

export const TOP_PRODUCT_LIST_LENGTH = 9;
export const CHANGE_QTY_PRODUCT_UP = "up";
export const CHANGE_QTY_PRODUCT_DOWN = "down";
